(defun my-default-color-theme ()
  "Color theme by edmond, created 2011-07-16."
  (interactive)
  (color-theme-install
   '(my-default-color-theme
     ((background-color . "unspecified-bg")
      (background-mode . dark)
      (background-toolbar-color . "#cf3ccf3ccf3c")
      (border-color . "black")
      (bottom-toolbar-shadow-color . "#79e77df779e7")
      (cursor-color . "black")
      (foreground-color . "unspecified-fg")
      (mouse-color . "black")
      (senator-eldoc-use-color . t)
      (top-toolbar-shadow-color . "#fffffbeeffff")
      (vc-annotate-very-old-color . "#0046FF")
      (viper-saved-cursor-color-in-replace-mode . "Red3"))
     ((Man-overstrike-face . bold)
      (Man-reverse-face . highlight)
      (Man-underline-face . underline)
      (align-highlight-change-face . highlight)
      (align-highlight-nochange-face . secondary-selection)
      (apropos-keybinding-face . underline)
      (apropos-label-face italic variable-pitch)
      (apropos-match-face . match)
      (apropos-property-face . bold-italic)
      (apropos-symbol-face . bold)
      (compilation-message-face . underline)
      (fci-rule-color . "#cccccc")
      (goto-address-mail-face . italic)
      (goto-address-mail-mouse-face . secondary-selection)
      (goto-address-url-face . bold)
      (goto-address-url-mouse-face . highlight)
      (info-lookup-highlight-face . match)
      (ispell-highlight-face . flyspell-incorrect)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (tags-tag-face . default)
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "unspecified-bg" :foreground "unspecified-fg" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 1 :width normal :foundry "default" :family "default"))))
     (Buffer-menu-buffer-face ((t (:bold t :weight bold))))
     (CUA-global-mark-face ((t (:background "cyan" :foreground "black"))))
     (CUA-rectangle-face ((t (:background "maroon" :foreground "white"))))
     (CUA-rectangle-noselect-face ((t (:background "dimgray" :foreground "white"))))
     (OrangeRed ((t (nil))))
     (antlr-font-lock-keyword-face ((t (:bold t :foreground "black" :weight bold))))
     (antlr-font-lock-literal-face ((t (:bold t :foreground "brown4" :weight bold))))
     (antlr-font-lock-ruledef-face ((t (:bold t :foreground "blue" :weight bold))))
     (antlr-font-lock-ruleref-face ((t (:foreground "blue4"))))
     (antlr-font-lock-tokendef-face ((t (:bold t :foreground "blue" :weight bold))))
     (antlr-font-lock-tokenref-face ((t (:foreground "orange4"))))
     (anything-header ((t (:background "grey" :foreground "black" :underline t))))
     (anything-isearch-match ((t (:background "Yellow"))))
     (anything-visible-mark ((t (:background "green" :foreground "black"))))
     (bbdb-company ((t (:italic t :slant italic))))
     (bbdb-field-name ((t (:foreground "lime green"))))
     (bbdb-field-value ((t (:foreground "white"))))
     (bbdb-name ((t (:foreground "lime green" :underline t))))
     (bg:erc-color-face0 ((t (:background "White"))))
     (bg:erc-color-face1 ((t (:background "black"))))
     (bg:erc-color-face10 ((t (:background "lightblue1"))))
     (bg:erc-color-face11 ((t (:background "cyan"))))
     (bg:erc-color-face12 ((t (:background "blue"))))
     (bg:erc-color-face13 ((t (:background "deeppink"))))
     (bg:erc-color-face14 ((t (:background "gray50"))))
     (bg:erc-color-face15 ((t (:background "gray90"))))
     (bg:erc-color-face2 ((t (:background "blue4"))))
     (bg:erc-color-face3 ((t (:background "green4"))))
     (bg:erc-color-face4 ((t (:background "red"))))
     (bg:erc-color-face5 ((t (:background "brown"))))
     (bg:erc-color-face6 ((t (:background "purple"))))
     (bg:erc-color-face7 ((t (:background "orange"))))
     (bg:erc-color-face8 ((t (:background "yellow"))))
     (bg:erc-color-face9 ((t (:background "green"))))
     (blank-space-face ((t (:background "gray80"))))
     (blank-tab-face ((t (:background "LightBlue" :foreground "DarkSlateGray"))))
     (blue ((t (:foreground "blue"))))
     (bold ((t (:bold t :weight bold :family "Arial"))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold :family "Arial"))))
     (border ((t (:background "black"))))
     (border-glyph ((t (:bold t :weight bold))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (buffers-tab ((t (:background "black" :foreground "LightSkyBlue"))))
     (button ((t (:underline t))))
     (c-nonbreakable-space-face ((t (:background "red"))))
     (calendar-today-face ((t (:foreground "deep sky blue" :underline t))))
     (change-log-acknowledgement ((t (:foreground "red1"))))
     (change-log-conditionals ((t (:foreground "yellow" :weight light))))
     (change-log-date ((t (:foreground "green"))))
     (change-log-email ((t (:foreground "yellow" :weight light))))
     (change-log-file ((t (:bold t :foreground "blue" :weight bold :family "Verdana"))))
     (change-log-function ((t (:foreground "yellow" :weight light))))
     (change-log-list ((t (:bold t :foreground "cyan" :weight bold))))
     (change-log-name ((t (:foreground "magenta"))))
     (clear-case-mode-string-face ((t (:bold t :background "grey" :foreground "black" :box (:line-width 2 :color "grey" :style released-button) :weight bold :height 0.9 :family "Arial"))))
     (clearcase-dired-checkedout-face ((t (:foreground "red"))))
     (cmode-bracket-face ((t (:bold t :weight bold))))
     (color-mode-face-@ ((t (:foreground "orange"))))
     (color-mode-face-a ((t (:foreground "blue"))))
     (color-mode-face-b ((t (:foreground "red"))))
     (color-mode-face-c ((t (:foreground "green3"))))
     (color-mode-face-d ((t (:background "red" :foreground "white"))))
     (color-mode-face-e ((t (:background "orange" :foreground "blue"))))
     (color-mode-face-f ((t (:background "blue" :foreground "yellow"))))
     (color-mode-face-g ((t (:background "lightblue" :foreground "brown"))))
     (color-mode-face-h ((t (:background "brown" :foreground "white"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "cyan"))))
     (comint-input-face ((t (:foreground "deepskyblue"))))
     (compilation-column-number ((t (:foreground "green"))))
     (compilation-error ((t (:foreground "red"))))
     (compilation-info ((t (:bold t :foreground "green" :weight bold))))
     (compilation-line-number ((t (:foreground "yellow" :weight light))))
     (compilation-warning ((t (:bold t :foreground "cyan" :weight bold))))
     (completions-common-part ((t (:stipple nil :background "unspecified-bg" :foreground "unspecified-fg" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 1 :width normal :foundry "default" :family "default"))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cparen-around-andor-face ((t (:bold t :foreground "maroon" :weight bold))))
     (cparen-around-begin-face ((t (:foreground "maroon"))))
     (cparen-around-conditional-face ((t (:bold t :foreground "RoyalBlue" :weight bold))))
     (cparen-around-define-face ((t (:bold t :foreground "Blue" :weight bold))))
     (cparen-around-lambda-face ((t (:foreground "LightSeaGreen"))))
     (cparen-around-letdo-face ((t (:bold t :foreground "LightSeaGreen" :weight bold))))
     (cparen-around-quote-face ((t (:foreground "SaddleBrown"))))
     (cparen-around-set!-face ((t (:foreground "OrangeRed"))))
     (cparen-around-syntax-rules-face ((t (:foreground "Magenta"))))
     (cparen-around-vector-face ((t (:foreground "chocolate"))))
     (cparen-binding-face ((t (:foreground "ForestGreen"))))
     (cparen-binding-list-face ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (cparen-conditional-clause-face ((t (:foreground "RoyalBlue"))))
     (cparen-normal-paren-face ((t (:foreground "grey50"))))
     (cperl-array-face ((t (:bold t :background "lightyellow2" :foreground "Blue" :weight bold))))
     (cperl-hash-face ((t (:italic t :bold t :background "lightyellow2" :foreground "Red" :slant italic :weight bold))))
     (cperl-here-face ((t (:foreground "green4"))))
     (cperl-invalid-face ((t (:foreground "white"))))
     (cperl-nonoverridable-face ((t (:foreground "chartreuse3"))))
     (cperl-pod-face ((t (:foreground "brown4"))))
     (cperl-pod-head-face ((t (:foreground "steelblue"))))
     (cscope-file-face ((t (:foreground "blue"))))
     (cscope-function-face ((t (:foreground "magenta"))))
     (cscope-line-face ((t (:foreground "green"))))
     (cscope-line-number-face ((t (:foreground "red"))))
     (cscope-mouse-face ((t (:background "blue" :foreground "white"))))
     (cursor ((t (:background "black"))))
     (custom-button ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-mouse ((t (nil))))
     (custom-button-pressed ((t (:foreground "lightgrey" :background "black" :box (:line-width 2 :style pressed-button)))))
     (custom-button-pressed-unraised ((t (:foreground "violet" :underline t))))
     (custom-button-unraised ((t (:underline t))))
     (custom-changed ((t (:background "blue" :foreground "white"))))
     (custom-comment ((t (:background "yellow3" :foreground "black"))))
     (custom-comment-tag ((t (:foreground "gray80"))))
     (custom-documentation ((t (:foreground "Grey"))))
     (custom-face-tag ((t (:bold t :foreground "light blue" :weight bold :family "helv"))))
     (custom-group-tag ((t (:bold t :foreground "light blue" :weight bold :height 1.2 :family "Sans Serif"))))
     (custom-group-tag-1 ((t (:bold t :foreground "pink" :weight bold :height 1.2 :family "Sans Serif"))))
     (custom-invalid ((t (:background "red1" :foreground "yellow1"))))
     (custom-link ((t (:foreground "cyan" :underline t))))
     (custom-modified ((t (:background "blue" :foreground "white"))))
     (custom-rogue ((t (:background "black" :foreground "pink"))))
     (custom-saved ((t (:underline t))))
     (custom-set ((t (:background "white" :foreground "blue"))))
     (custom-state ((t (:foreground "lime green"))))
     (custom-themed ((t (:background "blue" :foreground "white"))))
     (custom-variable-button ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag ((t (:bold t :foreground "light blue" :weight bold :family "helv"))))
     (custom-visibility ((t (:foreground "cyan" :underline t :height 0.8))))
     (cvs-filename-face ((t (:foreground "blue4"))))
     (cvs-handled-face ((t (:foreground "pink"))))
     (cvs-header-face ((t (:bold t :foreground "blue4" :weight bold))))
     (cvs-marked-face ((t (:bold t :foreground "green3" :weight bold))))
     (cvs-msg-face ((t (:italic t :slant italic))))
     (cvs-need-action-face ((t (:foreground "orange"))))
     (cvs-unknown-face ((t (:foreground "red"))))
     (cyan ((t (:foreground "cyan"))))
     (date ((t (:foreground "green"))))
     (diary-face ((t (:foreground "gold"))))
     (diff-added ((t (:italic t :bold t :foreground "green4" :slant italic :weight bold))))
     (diff-changed ((t (:italic t :bold t :foreground "yellow" :slant italic :weight bold))))
     (diff-context ((t (:foreground "grey50"))))
     (diff-file-header ((t (:bold t :foreground "cyan" :weight bold))))
     (diff-function ((t (:bold t :foreground "green" :weight bold))))
     (diff-header ((t (:bold t :foreground "green" :weight bold))))
     (diff-hunk-header ((t (:bold t :foreground "green" :weight bold))))
     (diff-index ((t (:bold t :foreground "cyan" :weight bold))))
     (diff-indicator-added ((t (:italic t :bold t :foreground "green4" :slant italic :weight bold))))
     (diff-indicator-changed ((t (:italic t :bold t :foreground "yellow" :slant italic :weight bold))))
     (diff-indicator-removed ((t (:italic t :bold t :foreground "red3" :slant italic :weight bold))))
     (diff-nonexistent ((t (:bold t :foreground "cyan" :weight bold))))
     (diff-refine-change ((t (:background "green"))))
     (diff-removed ((t (:italic t :bold t :foreground "red3" :slant italic :weight bold))))
     (dired-face-boring ((t (:foreground "RosyBrown"))))
     (dired-face-directory ((t (:foreground "Blue"))))
     (dired-face-executable ((t (:foreground "Green"))))
     (dired-face-flagged ((t (:bold t :foreground "Red" :weight bold))))
     (dired-face-header ((t (:background "grey75" :foreground "black"))))
     (dired-face-marked ((t (:bold t :foreground "Red" :weight bold))))
     (dired-face-permissions ((t (:background "grey75" :foreground "black"))))
     (dired-face-setuid ((t (:foreground "Red"))))
     (dired-face-socket ((t (:foreground "magenta"))))
     (dired-face-symlink ((t (:foreground "Purple"))))
     (display-time-mail-balloon-enhance-face ((t (:background "orange"))))
     (display-time-mail-balloon-gnus-group-face ((t (:foreground "blue"))))
     (display-time-time-balloon-face ((t (:foreground "red"))))
     (dropdown-list-face ((t (:stipple nil :background "lightyellow" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 1 :width normal :foundry "default" :family "default"))))
     (dropdown-list-selection-face ((t (:stipple nil :background "purple" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 1 :width normal :foundry "default" :family "default"))))
     (ebrowse-default-face ((t (nil))))
     (ebrowse-file-name-face ((t (:italic t :slant italic))))
     (ebrowse-member-attribute-face ((t (:foreground "red"))))
     (ebrowse-member-class-face ((t (:foreground "purple"))))
     (ebrowse-progress-face ((t (:background "blue"))))
     (ebrowse-root-class-face ((t (:bold t :foreground "blue" :weight bold))))
     (ebrowse-tree-mark-face ((t (:foreground "red"))))
     (ecb-bucket-token-face ((t (:bold t :weight bold))))
     (ecb-default-general-face ((t (nil))))
     (ecb-default-highlight-face ((t (:background "cornflower blue" :foreground "yellow"))))
     (ecb-directories-general-face ((t (nil))))
     (ecb-directory-face ((t (:background "cornflower blue" :foreground "yellow"))))
     (ecb-history-face ((t (:background "cornflower blue" :foreground "yellow"))))
     (ecb-history-general-face ((t (nil))))
     (ecb-method-face ((t (:background "cornflower blue" :foreground "yellow"))))
     (ecb-methods-general-face ((t (nil))))
     (ecb-source-face ((t (:background "cornflower blue" :foreground "yellow"))))
     (ecb-source-in-directories-buffer-face ((t (:foreground "medium blue"))))
     (ecb-sources-face ((t (:foreground "LightBlue1"))))
     (ecb-sources-general-face ((t (nil))))
     (ecb-token-header-face ((t (:background "SeaGreen1"))))
     (ecb-type-token-class-face ((t (:bold t :weight bold))))
     (ecb-type-token-enum-face ((t (:bold t :weight bold))))
     (ecb-type-token-group-face ((t (:bold t :foreground "dimgray" :weight bold))))
     (ecb-type-token-interface-face ((t (:bold t :weight bold))))
     (ecb-type-token-struct-face ((t (:bold t :weight bold))))
     (ecb-type-token-typedef-face ((t (:bold t :weight bold))))
     (edb-inter-field-face ((t (:foreground "deep sky blue"))))
     (edb-normal-summary-face ((t (:foreground "gold"))))
     (ediff-current-diff-A ((t (:background "yellow3" :foreground "blue3"))))
     (ediff-current-diff-Ancestor ((t (:background "magenta3" :foreground "black"))))
     (ediff-current-diff-B ((t (:bold t :background "yellow3" :foreground "magenta3" :weight bold))))
     (ediff-current-diff-C ((t (:bold t :background "yellow3" :foreground "cyan3" :weight bold))))
     (ediff-current-diff-face-A ((t (:background "pale green" :foreground "firebrick"))))
     (ediff-current-diff-face-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
     (ediff-current-diff-face-B ((t (:background "Yellow" :foreground "DarkOrchid"))))
     (ediff-current-diff-face-C ((t (:background "Pink" :foreground "Navy"))))
     (ediff-even-diff-A ((t (:bold t :background "light grey" :foreground "red3" :weight bold))))
     (ediff-even-diff-Ancestor ((t (:bold t :background "light grey" :foreground "cyan3" :weight bold))))
     (ediff-even-diff-B ((t (:bold t :background "Grey" :foreground "blue3" :weight bold))))
     (ediff-even-diff-C ((t (:bold t :background "light grey" :foreground "yellow3" :weight bold))))
     (ediff-even-diff-face-A ((t (:background "light grey" :foreground "Black"))))
     (ediff-even-diff-face-Ancestor ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-face-B ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-face-C ((t (:background "light grey" :foreground "Black"))))
     (ediff-fine-diff-A ((t (:bold t :background "sky blue" :foreground "white" :weight bold))))
     (ediff-fine-diff-Ancestor ((t (:background "green" :foreground "red3"))))
     (ediff-fine-diff-B ((t (:background "cyan3" :foreground "magenta3"))))
     (ediff-fine-diff-C ((t (:bold t :background "Turquoise" :foreground "yellow3" :weight bold))))
     (ediff-fine-diff-face-A ((t (:background "sky blue" :foreground "Navy"))))
     (ediff-fine-diff-face-Ancestor ((t (:background "Green" :foreground "Black"))))
     (ediff-fine-diff-face-B ((t (:background "cyan" :foreground "Black"))))
     (ediff-fine-diff-face-C ((t (:background "Turquoise" :foreground "Black"))))
     (ediff-odd-diff-A ((t (:bold t :background "black" :foreground "red3" :weight bold))))
     (ediff-odd-diff-Ancestor ((t (:bold t :background "black" :foreground "green3" :weight bold))))
     (ediff-odd-diff-B ((t (:bold t :background "black" :foreground "cyan3" :weight bold))))
     (ediff-odd-diff-C ((t (:bold t :background "black" :foreground "yellow3" :weight bold))))
     (ediff-odd-diff-face-A ((t (:background "Grey" :foreground "White"))))
     (ediff-odd-diff-face-Ancestor ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-face-B ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-face-C ((t (:background "Grey" :foreground "White"))))
     (eieio-custom-slot-tag-face ((t (:foreground "light blue"))))
     (eldoc-highlight-function-argument ((t (:bold t :weight bold))))
     (emacs-wiki-bad-link-face ((t (:bold t :foreground "coral" :underline "coral" :weight bold))))
     (emacs-wiki-link-face ((t (:bold t :foreground "cyan" :underline "cyan" :weight bold))))
     (erc-action-face ((t (:bold t :weight bold))))
     (erc-bold-face ((t (:bold t :weight bold))))
     (erc-current-nick-face ((t (:bold t :foreground "yellow" :weight bold))))
     (erc-dangerous-host-face ((t (:foreground "red"))))
     (erc-default-face ((t (nil))))
     (erc-direct-msg-face ((t (:foreground "IndianRed"))))
     (erc-error-face ((t (:background "Red" :foreground "White"))))
     (erc-fool-face ((t (:foreground "dim gray"))))
     (erc-highlight-face ((t (:bold t :foreground "pale green" :weight bold))))
     (erc-host-danger-face ((t (:foreground "red"))))
     (erc-input-face ((t (:foreground "brown"))))
     (erc-inverse-face ((t (:background "Black" :foreground "White"))))
     (erc-keyword-face ((t (:bold t :foreground "orange" :weight bold))))
     (erc-nick-default-face ((t (:bold t :weight semi-bold))))
     (erc-nick-msg-face ((t (:bold t :foreground "springgreen" :weight semi-bold))))
     (erc-notice-face ((t (:bold t :foreground "SlateBlue" :weight bold))))
     (erc-pal-face ((t (:foreground "pale green"))))
     (erc-prompt-face ((t (:bold t :background "lightBlue2" :foreground "Black" :weight bold))))
     (erc-timestamp-face ((t (:bold t :foreground "green" :weight bold))))
     (erc-underline-face ((t (:underline t))))
     (escape-glyph ((t (:foreground "cyan"))))
     (eshell-ls-archive-face ((t (:bold t :foreground "Orchid" :weight bold))))
     (eshell-ls-backup-face ((t (:foreground "OrangeRed"))))
     (eshell-ls-clutter-face ((t (:bold t :foreground "OrangeRed" :weight bold))))
     (eshell-ls-directory-face ((t (:bold t :foreground "Blue" :weight bold))))
     (eshell-ls-executable-face ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (eshell-ls-missing-face ((t (:bold t :foreground "Red" :weight bold))))
     (eshell-ls-picture-face ((t (:foreground "Violet"))))
     (eshell-ls-product-face ((t (:foreground "OrangeRed"))))
     (eshell-ls-readonly-face ((t (:foreground "Brown"))))
     (eshell-ls-special-face ((t (:bold t :foreground "Magenta" :weight bold))))
     (eshell-ls-symlink-face ((t (:bold t :foreground "DarkCyan" :weight bold))))
     (eshell-ls-text-face ((t (:foreground "medium aquamarine"))))
     (eshell-ls-todo-face ((t (:bold t :foreground "aquamarine" :weight bold))))
     (eshell-ls-unreadable-face ((t (:foreground "Grey30"))))
     (eshell-prompt-face ((t (:bold t :foreground "Red" :weight bold :foundry "neep" :family "alt"))))
     (eshell-test-failed-face ((t (:bold t :foreground "OrangeRed" :weight bold))))
     (eshell-test-ok-face ((t (:bold t :foreground "Green" :weight bold))))
     (esk-paren-face ((t (:foreground "grey50"))))
     (excerpt ((t (:italic t :slant italic))))
     (extra-whitespace-face ((t (:background "pale green"))))
     (face-1 ((t (:stipple nil :foreground "royal blue" :family "andale mono"))))
     (face-2 ((t (:stipple nil :foreground "DeepSkyBlue1" :overline nil :underline nil :slant normal :foundry "outline" :family "andale mono"))))
     (face-3 ((t (:stipple nil :foreground "NavajoWhite3"))))
     (ff-paths-non-existant-file-face ((t (:bold t :foreground "NavyBlue" :weight bold))))
     (ffap ((t (:background "green" :foreground "black"))))
     (fg:black ((t (:foreground "black"))))
     (fg:erc-color-face0 ((t (:foreground "White"))))
     (fg:erc-color-face1 ((t (:foreground "black"))))
     (fg:erc-color-face10 ((t (:foreground "lightblue1"))))
     (fg:erc-color-face11 ((t (:foreground "cyan"))))
     (fg:erc-color-face12 ((t (:foreground "blue"))))
     (fg:erc-color-face13 ((t (:foreground "deeppink"))))
     (fg:erc-color-face14 ((t (:foreground "gray50"))))
     (fg:erc-color-face15 ((t (:foreground "gray90"))))
     (fg:erc-color-face2 ((t (:foreground "blue4"))))
     (fg:erc-color-face3 ((t (:foreground "green4"))))
     (fg:erc-color-face4 ((t (:foreground "red"))))
     (fg:erc-color-face5 ((t (:foreground "brown"))))
     (fg:erc-color-face6 ((t (:foreground "purple"))))
     (fg:erc-color-face7 ((t (:foreground "orange"))))
     (fg:erc-color-face8 ((t (:foreground "yellow"))))
     (fg:erc-color-face9 ((t (:foreground "green"))))
     (file-name-shadow ((t (:foreground "yellow"))))
     (fixed ((t (:bold t :weight bold))))
     (fixed-pitch ((t (:family "Monospace"))))
     (fl-comment-face ((t (:foreground "medium purple"))))
     (fl-doc-string-face ((t (:foreground "purple"))))
     (fl-function-name-face ((t (:foreground "green"))))
     (fl-keyword-face ((t (:foreground "LightGreen"))))
     (fl-string-face ((t (:foreground "light coral"))))
     (fl-type-face ((t (:foreground "cyan"))))
     (flash-paren-face-off ((t (nil))))
     (flash-paren-face-on ((t (nil))))
     (flash-paren-face-region ((t (nil))))
     (flyspell-duplicate ((t (:bold t :foreground "Gold3" :underline t :weight bold))))
     (flyspell-incorrect ((t (:bold t :foreground "OrangeRed" :underline t :weight bold))))
     (font-latex-bold-face ((t (:bold t :foreground "DarkOliveGreen" :weight bold))))
     (font-latex-italic-face ((t (:italic t :foreground "DarkOliveGreen" :slant italic))))
     (font-latex-math-face ((t (:foreground "SaddleBrown"))))
     (font-latex-sedate-face ((t (:foreground "DimGray"))))
     (font-latex-string-face ((t (:foreground "RosyBrown"))))
     (font-latex-warning-face ((t (:bold t :foreground "Red" :weight bold))))
     (font-lock-builtin-face ((t (:bold t :foreground "blue" :weight bold))))
     (font-lock-comment-delimiter-face ((t (:foreground "red1"))))
     (font-lock-comment-face ((t (:foreground "red1" :family "helvetica"))))
     (font-lock-constant-face ((t (:foreground "magenta"))))
     (font-lock-doc-face ((t (:foreground "green"))))
     (font-lock-doc-string-face ((t (:foreground "gold"))))
     (font-lock-emphasized-face ((t (:bold t :background "lightyellow2" :weight bold))))
     (font-lock-exit-face ((t (:foreground "green"))))
     (font-lock-function-name-face ((t (:bold t :foreground "blue" :weight bold :foundry "outline" :family "Verdana"))))
     (font-lock-keyword-face ((t (:bold t :foreground "cyan" :weight bold :foundry "outline" :family "verdana"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-other-emphasized-face ((t (:bold t :foreground "gold1" :weight bold))))
     (font-lock-other-type-face ((t (:bold t :foreground "gold1" :weight bold))))
     (font-lock-preprocessor-face ((t (:bold t :foreground "blue" :weight bold))))
     (font-lock-reference-face ((t (:foreground "LightSteelBlue"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-special-comment-face ((t (:foreground "blue4"))))
     (font-lock-special-keyword-face ((t (:foreground "red4"))))
     (font-lock-string-face ((t (:foreground "green"))))
     (font-lock-type-face ((t (:foreground "green" :family "Verdana"))))
     (font-lock-variable-name-face ((t (:foreground "yellow" :weight light))))
     (font-lock-warning-face ((t (:foreground "red"))))
     (fringe ((t (:background "grey10" :foundry "outline" :family "courier new"))))
     (gdb-arrow-face ((t (:bold t :background "yellow" :foreground "red" :weight bold))))
     (gnu-cite-face-3 ((t (nil))))
     (gnu-cite-face-4 ((t (nil))))
     (gnus-cite-attribution-face ((t (:bold t :foreground "Wheat" :weight bold :family "arial"))))
     (gnus-cite-face-1 ((t (:foreground "wheat"))))
     (gnus-cite-face-10 ((t (:foreground "wheat"))))
     (gnus-cite-face-11 ((t (:foreground "turquoise"))))
     (gnus-cite-face-2 ((t (:foreground "cyan"))))
     (gnus-cite-face-3 ((t (:foreground "light yellow"))))
     (gnus-cite-face-4 ((t (:foreground "light pink"))))
     (gnus-cite-face-5 ((t (:foreground "pale green"))))
     (gnus-cite-face-6 ((t (:foreground "beige"))))
     (gnus-cite-face-7 ((t (:foreground "orange"))))
     (gnus-cite-face-8 ((t (:foreground "magenta"))))
     (gnus-cite-face-9 ((t (:foreground "violet"))))
     (gnus-cite-face-list ((t (:bold t :foreground "red" :weight bold))))
     (gnus-emphasis-bold ((t (:foreground "yellow2" :family "Arial"))))
     (gnus-emphasis-bold-italic ((t (:foreground "yellow2" :family "arial"))))
     (gnus-emphasis-highlight-words ((t (:background "black" :foreground "yellow"))))
     (gnus-emphasis-italic ((t (:foreground "yellow2" :family "Arial"))))
     (gnus-emphasis-strikethru ((t (nil))))
     (gnus-emphasis-underline ((t (:foreground "yellow2"))))
     (gnus-emphasis-underline-bold ((t (:foreground "yellow2" :family "Arial"))))
     (gnus-emphasis-underline-bold-italic ((t (:foreground "yellow2" :family "Arial"))))
     (gnus-emphasis-underline-italic ((t (:foreground "yellow2" :family "Arial"))))
     (gnus-filterhist-face-1 ((t (nil))))
     (gnus-group-mail-1-empty-face ((t (:foreground "aquamarine1"))))
     (gnus-group-mail-1-face ((t (:bold t :foreground "aquamarine1" :weight bold))))
     (gnus-group-mail-2-empty-face ((t (:foreground "aquamarine2"))))
     (gnus-group-mail-2-face ((t (:bold t :foreground "aquamarine2" :weight bold))))
     (gnus-group-mail-3-empty-face ((t (:foreground "aquamarine3"))))
     (gnus-group-mail-3-face ((t (:bold t :foreground "aquamarine3" :weight bold))))
     (gnus-group-mail-low-empty-face ((t (:foreground "aquamarine4"))))
     (gnus-group-mail-low-face ((t (:bold t :foreground "aquamarine4" :weight bold))))
     (gnus-group-news-1-empty-face ((t (:foreground "PaleTurquoise" :family "courier"))))
     (gnus-group-news-1-face ((t (:bold t :foreground "PaleTurquoise" :weight bold :family "courier"))))
     (gnus-group-news-2-empty-face ((t (:foreground "turquoise"))))
     (gnus-group-news-2-face ((t (:bold t :foreground "turquoise" :weight bold))))
     (gnus-group-news-3-empty-face ((t (:foreground "deep sky blue"))))
     (gnus-group-news-3-face ((t (:bold t :foreground "deep sky blue" :weight bold))))
     (gnus-group-news-4-empty-face ((t (:foreground "Aquamarine"))))
     (gnus-group-news-4-face ((t (:bold t :weight bold))))
     (gnus-group-news-5-empty-face ((t (:foreground "MediumAquamarine"))))
     (gnus-group-news-5-face ((t (:bold t :weight bold))))
     (gnus-group-news-6-empty-face ((t (:foreground "MediumAquamarine"))))
     (gnus-group-news-6-face ((t (:bold t :weight bold))))
     (gnus-group-news-low-empty-face ((t (:foreground "DarkTurquoise"))))
     (gnus-group-news-low-face ((t (:bold t :foreground "DarkTurquoise" :weight bold))))
     (gnus-header-content-face ((t (:foreground "gold" :family "helvetica"))))
     (gnus-header-from-face ((t (:foreground "gold" :family "helvetica"))))
     (gnus-header-name-face ((t (:foreground "deep sky blue" :family "helvetica"))))
     (gnus-header-newsgroups-face ((t (:foreground "gold"))))
     (gnus-header-subject-face ((t (:foreground "gold" :family "helvetica"))))
     (gnus-picon-face ((t (:background "white" :foreground "black"))))
     (gnus-picon-xbm-face ((t (:background "white" :foreground "black"))))
     (gnus-picons-face ((t (:background "white" :foreground "black"))))
     (gnus-picons-xbm-face ((t (:background "white" :foreground "black"))))
     (gnus-server-agent-face ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
     (gnus-server-closed-face ((t (:italic t :foreground "Light Steel Blue" :slant italic))))
     (gnus-server-denied-face ((t (:bold t :foreground "Pink" :weight semi-bold))))
     (gnus-server-offline-face ((t (:bold t :foreground "Yellow" :weight bold))))
     (gnus-server-opened-face ((t (:bold t :foreground "Green1" :weight semi-bold))))
     (gnus-signature-face ((t (:foreground "gold"))))
     (gnus-splash ((t (:foreground "Brown"))))
     (gnus-splash-face ((t (:foreground "firebrick"))))
     (gnus-summary-cancelled-face ((t (:background "black" :foreground "deep sky blue"))))
     (gnus-summary-high-ancient-face ((t (:bold t :foreground "deep sky blue" :weight bold))))
     (gnus-summary-high-read-face ((t (:bold t :foreground "deep sky blue" :weight bold))))
     (gnus-summary-high-ticked-face ((t (:bold t :foreground "deep sky blue" :weight bold))))
     (gnus-summary-high-undownloaded-face ((t (:bold t :foreground "LightGray" :weight bold))))
     (gnus-summary-high-unread-face ((t (:bold t :foreground "lime green" :weight bold))))
     (gnus-summary-low-ancient-face ((t (:italic t :foreground "deep sky blue" :slant italic))))
     (gnus-summary-low-read-face ((t (:italic t :foreground "deep sky blue" :slant italic))))
     (gnus-summary-low-ticked-face ((t (:italic t :foreground "deep sky blue" :slant italic))))
     (gnus-summary-low-undownloaded-face ((t (:italic t :foreground "LightGray" :slant italic :weight normal))))
     (gnus-summary-low-unread-face ((t (:italic t :foreground "lime green" :slant italic))))
     (gnus-summary-normal-ancient-face ((t (:foreground "deep sky blue" :family "neep"))))
     (gnus-summary-normal-read-face ((t (:foreground "deep sky blue" :family "neep"))))
     (gnus-summary-normal-ticked-face ((t (:foreground "deep sky blue" :family "neep"))))
     (gnus-summary-normal-undownloaded-face ((t (:foreground "LightGray" :weight normal))))
     (gnus-summary-normal-unread-face ((t (:foreground "lime green" :family "neep"))))
     (gnus-summary-selected-face ((t (:foreground "gold" :underline t :family "neep"))))
     (gnus-x-face ((t (:background "white" :foreground "black"))))
     (green ((t (:foreground "green"))))
     (gui-button-face ((t (:background "grey75" :foreground "black"))))
     (gui-element ((t (:background "Gray"))))
     (header-line ((t (:background "grey" :foreground "black" :underline t :family "Arial"))))
     (help-argument-name ((t (nil))))
     (hi-black-b ((t (:bold t :weight bold))))
     (hi-black-hb ((t (:bold t :weight bold :height 1.67 :family "Sans Serif"))))
     (hi-blue ((t (:background "light blue" :foreground "black"))))
     (hi-blue-b ((t (:bold t :foreground "blue" :weight bold))))
     (hi-green ((t (:background "green" :foreground "black"))))
     (hi-green-b ((t (:bold t :foreground "green" :weight bold))))
     (hi-pink ((t (:background "pink" :foreground "black"))))
     (hi-red-b ((t (:bold t :foreground "red" :weight bold))))
     (hi-yellow ((t (:background "yellow" :foreground "black"))))
     (highlight ((t (:background "green" :foreground "black"))))
     (highlight-changes-delete-face ((t (:foreground "red" :underline t))))
     (highlight-changes-face ((t (:foreground "red"))))
     (highline-face ((t (:background "black" :foreground "white"))))
     (holiday-face ((t (:background "blue4" :foreground "IndianRed1"))))
     (horizontal-divider ((t (:background "gray16" :foreground "#00ff00"))))
     (hproperty:but-face ((t (:bold t :background "wheat" :foreground "medium violet red" :weight bold))))
     (hproperty:flash-face ((t (:bold t :background "wheat" :foreground "gray80" :weight bold))))
     (hproperty:highlight-face ((t (:bold t :background "wheat" :foreground "red" :weight bold))))
     (hproperty:item-face ((t (:bold t :weight bold))))
     (html-helper-bold-face ((t (:bold t :weight bold))))
     (html-helper-bold-italic-face ((t (nil))))
     (html-helper-builtin-face ((t (:foreground "blue3" :underline t))))
     (html-helper-italic-face ((t (:bold t :foreground "yellow" :weight bold))))
     (html-helper-underline-face ((t (:underline t))))
     (html-tag-face ((t (:foreground "Blue"))))
     (hyper-apropos-documentation ((t (:foreground "white"))))
     (hyper-apropos-heading ((t (:bold t :weight bold))))
     (hyper-apropos-hyperlink ((t (:foreground "sky blue"))))
     (hyper-apropos-major-heading ((t (:bold t :weight bold))))
     (hyper-apropos-section-heading ((t (:bold t :weight bold))))
     (hyper-apropos-warning ((t (:bold t :foreground "red" :weight bold))))
     (ibuffer-deletion-face ((t (:foreground "red"))))
     (ibuffer-marked-face ((t (:foreground "red"))))
     (idlwave-help-link-face ((t (:foreground "Blue"))))
     (idlwave-shell-bp-face ((t (:background "Pink" :foreground "Black"))))
     (ido-first-match ((t (:bold t :weight bold))))
     (ido-first-match-face ((t (:bold t :weight bold))))
     (ido-incomplete-regexp ((t (:foreground "red"))))
     (ido-indicator ((t (:background "red" :foreground "yellow" :width condensed))))
     (ido-indicator-face ((t (:background "red" :foreground "yellow" :width condensed))))
     (ido-only-match ((t (:foreground "ForestGreen"))))
     (ido-only-match-face ((t (:foreground "ForestGreen"))))
     (ido-subdir ((t (:foreground "red"))))
     (ido-subdir-face ((t (:foreground "MediumSlateBlue"))))
     (info-header-node ((t (:italic t :bold t :foreground "white" :slant italic :weight bold))))
     (info-header-xref ((t (:foreground "cyan" :underline t))))
     (info-menu-6 ((t (nil))))
     (info-menu-header ((t (:bold t :underline t :weight bold :family "helv"))))
     (info-menu-star ((t (:foreground "red1"))))
     (info-node ((t (:italic t :bold t :foreground "white" :slant italic :weight bold))))
     (info-title-1 ((t (:bold t :foreground "yellow" :weight bold :family "helv"))))
     (info-title-2 ((t (:bold t :foreground "lightblue" :weight bold :family "helv"))))
     (info-title-3 ((t (:bold t :weight bold :family "helv"))))
     (info-title-4 ((t (:bold t :weight bold :family "helv"))))
     (info-xref ((t (:foreground "cyan" :underline t))))
     (info-xref-visited ((t (:foreground "violet" :underline t))))
     (isearch ((t (:background "magenta4" :foreground "cyan1"))))
     (isearch-fail ((t (:background "red"))))
     (isearch-secondary ((t (:foreground "red3"))))
     (ispell-face ((t (:bold t :background "#3454b4" :foreground "yellow" :weight bold))))
     (iswitchb-current-match ((t (:bold t :foreground "blue" :weight bold))))
     (iswitchb-invalid-regexp ((t (:foreground "red"))))
     (iswitchb-single-match ((t (:foreground "red1"))))
     (iswitchb-virtual-matches ((t (:bold t :foreground "blue" :weight bold))))
     (italic ((t (:underline t))))
     (jde-bug-breakpoint-cursor ((t (:background "brown" :foreground "cyan"))))
     (jde-bug-breakpoint-marker ((t (:background "yellow" :foreground "red"))))
     (jde-db-active-breakpoint-face ((t (:background "red" :foreground "black"))))
     (jde-db-requested-breakpoint-face ((t (:background "yellow" :foreground "black"))))
     (jde-db-spec-breakpoint-face ((t (:background "green" :foreground "black"))))
     (jde-java-font-lock-api-face ((t (:foreground "dark goldenrod"))))
     (jde-java-font-lock-bold-face ((t (:bold t :weight bold))))
     (jde-java-font-lock-code-face ((t (nil))))
     (jde-java-font-lock-constant-face ((t (:foreground "CadetBlue"))))
     (jde-java-font-lock-doc-tag-face ((t (:foreground "green4"))))
     (jde-java-font-lock-italic-face ((t (:italic t :slant italic))))
     (jde-java-font-lock-link-face ((t (:foreground "cadetblue" :underline t :slant normal))))
     (jde-java-font-lock-modifier-face ((t (:foreground "Orchid"))))
     (jde-java-font-lock-number-face ((t (:foreground "RosyBrown"))))
     (jde-java-font-lock-operator-face ((t (:foreground "medium blue"))))
     (jde-java-font-lock-package-face ((t (:foreground "blue3"))))
     (jde-java-font-lock-pre-face ((t (nil))))
     (jde-java-font-lock-underline-face ((t (:underline t))))
     (kai-gnus-cite-face-1 ((t (:foreground "LightCyan4"))))
     (kai-gnus-cite-face-2 ((t (:foreground "LightSkyBlue2"))))
     (kai-gnus-cite-face-3 ((t (:foreground "DodgerBlue3"))))
     (kai-gnus-group-mail-face ((t (:foreground "darkslategrey"))))
     (kai-gnus-group-nonempty-mail-face ((t (:foreground "DarkRed"))))
     (kai-gnus-group-starred-face ((t (:foreground "grey50"))))
     (lazy-highlight ((t (:background "turquoise3"))))
     (lazy-highlight-face ((t (:bold t :foreground "dark magenta" :weight bold))))
     (left-margin ((t (:background "darkblue" :foreground "yellow"))))
     (linemenu-face ((t (:background "gray30"))))
     (link ((t (:foreground "cyan" :underline t))))
     (link-visited ((t (:foreground "violet" :underline t))))
     (list-mode-item-selected ((t (:background "gray68" :foreground "dark green"))))
     (log-view-file-face ((t (:bold t :background "grey70" :weight bold))))
     (log-view-message-face ((t (:background "grey85"))))
     (m4-face ((t (:background "gray90" :foreground "orange3"))))
     (magenta ((t (:foreground "magenta"))))
     (magit-branch ((t (:bold t :weight bold))))
     (magit-diff-add ((t (:foreground "green3"))))
     (magit-diff-del ((t (:foreground "red3"))))
     (magit-diff-file-header ((t (nil))))
     (magit-diff-hunk-header ((t (:italic t :slant italic))))
     (magit-diff-none ((t (nil))))
     (magit-header ((t (nil))))
     (magit-item-highlight ((t (nil))))
     (magit-item-mark ((t (nil))))
     (magit-log-graph ((t (nil))))
     (magit-log-head-label-bisect-bad ((t (nil))))
     (magit-log-head-label-bisect-good ((t (nil))))
     (magit-log-head-label-local ((t (nil))))
     (magit-log-head-label-remote ((t (nil))))
     (magit-log-head-label-tags ((t (nil))))
     (magit-log-message ((t (nil))))
     (magit-log-sha1 ((t (nil))))
     (magit-log-tag-label ((t (nil))))
     (magit-section-title ((t (:bold t :weight bold))))
     (makefile-space-face ((t (:background "hotpink"))))
     (man-bold ((t (:bold t :weight bold))))
     (man-heading ((t (:bold t :weight bold))))
     (man-italic ((t (:foreground "yellow"))))
     (man-xref ((t (:underline t))))
     (match ((t (:background "blue" :foreground "white"))))
     (menu ((t (:background "darkslategrey" :foreground "wheat" :family "helvetica"))))
     (message-cited-text ((t (:foreground "orange"))))
     (message-cited-text-face ((t (:foreground "gold"))))
     (message-header-cc-face ((t (:bold t :foreground "green4" :weight bold :family "helvetica"))))
     (message-header-contents ((t (:foreground "white"))))
     (message-header-name-face ((t (:foreground "deep sky blue"))))
     (message-header-newsgroups-face ((t (:italic t :bold t :foreground "gold" :slant italic :weight bold))))
     (message-header-other-face ((t (:foreground "gold"))))
     (message-header-subject-face ((t (:foreground "gold"))))
     (message-header-to-face ((t (:bold t :foreground "gold" :weight bold :family "helvetica"))))
     (message-header-xheader-face ((t (:foreground "blue"))))
     (message-headers ((t (:bold t :foreground "orange" :weight bold))))
     (message-highlighted-header-contents ((t (:bold t :weight bold))))
     (message-mml-face ((t (:bold t :foreground "khaki" :weight bold))))
     (message-separator-face ((t (:foreground "lime green"))))
     (message-url ((t (:bold t :foreground "pink" :weight bold))))
     (minibuffer-prompt ((t (:foreground "cyan"))))
     (mmm-default-submode-face ((t (:background "#c0c0c5"))))
     (mmm-face ((t (:background "black" :foreground "green"))))
     (mode-line ((t (:background "grey" :foreground "black" :family "neep"))))
     (mode-line-buffer-id ((t (:bold t :weight bold :family "Arial"))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:background "green" :foreground "black"))))
     (mode-line-inactive ((t (:background "grey" :foreground "black"))))
     (modeline-mousable ((t (:background "dodgerblue" :foreground "black" :family "Arial"))))
     (modeline-mousable-minor-mode ((t (:background "dodgerblue" :foreground "black" :family "Arial"))))
     (mouse ((t (:background "black"))))
     (mpg123-face-cur ((t (:background "#004080" :foreground "yellow"))))
     (mpg123-face-slider ((t (:background "yellow" :foreground "black"))))
     (my-summary-highlight-face ((t (:foreground "White"))))
     (my-tab-face ((t (:background "SlateBlue1"))))
     (my-url-face ((t (:foreground "PaleTurquoise"))))
     (next-error ((t (:background "blue" :foreground "white"))))
     (nil ((t (nil))))
     (nobreak-space ((t (:background "magenta"))))
     (overlay-empty-face ((t (nil))))
     (p4-depot-added-face ((t (:foreground "steelblue1"))))
     (p4-depot-deleted-face ((t (:foreground "red"))))
     (p4-depot-unmapped-face ((t (:foreground "grey90"))))
     (p4-diff-change-face ((t (:foreground "dark green"))))
     (p4-diff-del-face ((t (:bold t :foreground "salmon" :weight bold))))
     (p4-diff-file-face ((t (:background "blue"))))
     (p4-diff-head-face ((t (:background "blue"))))
     (p4-diff-ins-face ((t (:foreground "steelblue1"))))
     (paren-blink-off ((t (:foreground "gray80"))))
     (paren-blink-on ((t (:foreground "purple"))))
     (paren-face ((t (:background "lightgoldenrod"))))
     (paren-face-match ((t (:background "turquoise"))))
     (paren-face-mismatch ((t (:background "purple" :foreground "white"))))
     (paren-face-no-match ((t (:background "yellow" :foreground "black"))))
     (paren-match ((t (:background "dark blue"))))
     (paren-mismatch ((t (:background "DeepPink" :foreground "LightSkyBlue"))))
     (paren-mismatch-face ((t (:background "DeepPink" :foreground "white"))))
     (paren-no-match-face ((t (:background "yellow" :foreground "white"))))
     (pointer ((t (:foreground "White"))))
     (primary-selection ((t (:background "lightgoldenrod2"))))
     (py-XXX-tag-face ((t (:foreground "red1"))))
     (py-builtins-face ((t (:bold t :foreground "cyan" :weight bold))))
     (py-decorators-face ((t (:bold t :foreground "cyan" :weight bold))))
     (py-pseudo-keyword-face ((t (:bold t :foreground "cyan" :weight bold))))
     (qt-classes-face ((t (:foreground "Red"))))
     (query-replace ((t (:background "magenta4" :foreground "cyan1"))))
     (reb-match-0 ((t (:background "lightblue"))))
     (reb-match-1 ((t (:background "aquamarine"))))
     (reb-match-2 ((t (:background "springgreen"))))
     (reb-match-3 ((t (:background "yellow"))))
     (red ((t (:foreground "red"))))
     (region ((t (:background "blue" :foreground "white"))))
     (right-margin ((t (:background "darkblue" :foreground "yellow"))))
     (rpm-spec-dir-face ((t (:foreground "green"))))
     (rpm-spec-doc-face ((t (:foreground "magenta"))))
     (rpm-spec-ghost-face ((t (:foreground "red"))))
     (rpm-spec-macro-face ((t (:foreground "purple"))))
     (rpm-spec-package-face ((t (:foreground "red"))))
     (rpm-spec-tag-face ((t (:foreground "blue"))))
     (rpm-spec-var-face ((t (:foreground "maroon"))))
     (ruler-mode-column-number-face ((t (:stipple nil :background "grey76" :foreground "black" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "outline" :family "andale mono"))))
     (ruler-mode-current-column-face ((t (:bold t :stipple nil :background "grey76" :foreground "yellow" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight bold :width normal :foundry "outline" :family "andale mono"))))
     (ruler-mode-default-face ((t (:stipple nil :background "grey76" :foreground "grey64" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "outline" :family "andale mono"))))
     (ruler-mode-fill-column-face ((t (:stipple nil :background "grey76" :foreground "red" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "outline" :family "andale mono"))))
     (ruler-mode-margins-face ((t (:stipple nil :background "grey64" :foreground "grey64" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "outline" :family "andale mono"))))
     (ruler-mode-tab-stop-face ((t (:stipple nil :background "grey76" :foreground "steelblue" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "outline" :family "andale mono"))))
     (scroll-bar ((t (:background "grey75"))))
     (searchm-buffer ((t (:bold t :background "white" :foreground "red" :weight bold))))
     (searchm-button ((t (:bold t :background "CadetBlue" :foreground "white" :weight bold))))
     (searchm-field ((t (:background "grey89"))))
     (searchm-field-label ((t (:bold t :weight bold))))
     (searchm-highlight ((t (:bold t :background "darkseagreen2" :foreground "black" :weight bold))))
     (secondary-selection ((t (:background "cyan" :foreground "black"))))
     (semantic-dirty-token-face ((t (:background "lightyellow"))))
     (semantic-intangible-face ((t (:foreground "gray25"))))
     (semantic-read-only-face ((t (:background "gray25"))))
     (semantic-unmatched-syntax-face ((t (:underline "red"))))
     (senator-intangible-face ((t (:foreground "gray25"))))
     (senator-momentary-highlight-face ((t (:background "gray70"))))
     (senator-read-only-face ((t (:background "#CCBBBB"))))
     (setnu-line-number-face ((t (:bold t :background "Grey15" :foreground "White" :weight bold))))
     (sgml-comment-face ((t (:italic t :foreground "SeaGreen" :slant italic))))
     (sgml-doctype-face ((t (:bold t :foreground "FireBrick" :weight bold))))
     (sgml-end-tag-face ((t (:stipple nil :background "white" :foreground "SlateBlue" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 116 :width normal :foundry "monotype" :family "courier new"))))
     (sgml-entity-face ((t (:stipple nil :background "SlateBlue" :foreground "Red" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 116 :width normal :foundry "monotype" :family "courier new"))))
     (sgml-ignored-face ((t (:background "gray60" :foreground "gray40"))))
     (sgml-ms-end-face ((t (:foreground "green"))))
     (sgml-ms-start-face ((t (:foreground "yellow"))))
     (sgml-pi-face ((t (:bold t :foreground "gray40" :weight bold))))
     (sgml-sgml-face ((t (:bold t :foreground "gray40" :weight bold))))
     (sgml-short-ref-face ((t (:foreground "deep sky blue"))))
     (sgml-shortref-face ((t (:bold t :foreground "gray40" :weight bold))))
     (sgml-start-tag-face ((t (:stipple nil :background "white" :foreground "SlateBlue" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 116 :width normal :foundry "monotype" :family "courier new"))))
     (sh-heredoc-face ((t (:foreground "tan"))))
     (shadow ((t (:foreground "yellow"))))
     (shell-input-face ((t (:bold t :background "wheat" :foreground "blue" :weight bold))))
     (shell-option-face ((t (:foreground "blue4"))))
     (shell-output-2-face ((t (:foreground "green4"))))
     (shell-output-3-face ((t (:foreground "green4"))))
     (shell-output-face ((t (:bold t :weight bold))))
     (shell-prompt-face ((t (:foreground "red4"))))
     (show-block-face1 ((t (:background "gray10"))))
     (show-block-face2 ((t (:background "gray15"))))
     (show-block-face3 ((t (:background "gray20"))))
     (show-block-face4 ((t (:background "gray25"))))
     (show-block-face5 ((t (:background "gray30"))))
     (show-block-face6 ((t (:background "gray35"))))
     (show-block-face7 ((t (:background "gray40"))))
     (show-block-face8 ((t (:background "gray45"))))
     (show-block-face9 ((t (:background "gray50"))))
     (show-paren-match ((t (:background "steelblue3"))))
     (show-paren-mismatch ((t (:background "purple" :foreground "white"))))
     (show-tabs-space-face ((t (:foreground "yellow"))))
     (show-tabs-tab-face ((t (:foreground "red"))))
     (show-trailing-whitespace ((t (:background "red" :foreground "blue"))))
     (smerge-base-face ((t (:foreground "red"))))
     (smerge-markers-face ((t (:background "grey85"))))
     (smerge-mine-face ((t (:foreground "blue"))))
     (smerge-other-face ((t (:foreground "darkgreen"))))
     (special-string-face ((t (:foreground "light green"))))
     (speedbar-button-face ((t (:foreground "green3"))))
     (speedbar-directory-face ((t (:foreground "light blue"))))
     (speedbar-file-face ((t (:foreground "cyan"))))
     (speedbar-highlight-face ((t (:background "sea green"))))
     (speedbar-selected-face ((t (:foreground "red" :underline t))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
     (speedbar-tag-face ((t (:foreground "yellow"))))
     (strokes-char-face ((t (:background "lightgray"))))
     (swbuff-current-buffer-face ((t (:bold t :foreground "red" :weight bold))))
     (tabbar-button-face ((t (:background "black" :foreground "#00cc00" :box (:line-width 2 :color "black" :style released-button)))))
     (tabbar-default-face ((t (:background "black" :foreground "#00cc00"))))
     (tabbar-selected-face ((t (:background "black" :foreground "springgreen" :box (:line-width 2 :color "black" :style released-button)))))
     (tabbar-separator-face ((t (:background "black" :foreground "#00cc00"))))
     (tabbar-unselected-face ((t (:background "black" :foreground "seagreen" :box (:line-width 2 :color "black" :style pressed-button)))))
     (template-message-face ((t (:bold t :weight bold))))
     (term-black ((t (:foreground "black" :foundry "adobe" :family "courier"))))
     (term-blackbg ((t (:background "black" :foundry "adobe" :family "courier"))))
     (term-blue ((t (:foreground "blue" :foundry "adobe" :family "courier"))))
     (term-blue-bold-face ((t (:bold t :background "snow2" :foreground "blue" :weight bold))))
     (term-blue-face ((t (:foreground "blue"))))
     (term-blue-inv-face ((t (:background "blue"))))
     (term-blue-ul-face ((t (:background "snow2" :foreground "blue" :underline t))))
     (term-bluebg ((t (:background "blue" :foundry "adobe" :family "courier"))))
     (term-bold ((t (:bold t :weight bold :foundry "adobe" :family "courier"))))
     (term-cyan ((t (:foreground "cyan" :foundry "adobe" :family "courier"))))
     (term-cyan-bold-face ((t (:bold t :background "snow2" :foreground "cyan" :weight bold))))
     (term-cyan-face ((t (:foreground "cyan"))))
     (term-cyan-inv-face ((t (:background "cyan"))))
     (term-cyan-ul-face ((t (:background "snow2" :foreground "cyan" :underline t))))
     (term-cyanbg ((t (:background "cyan" :foundry "adobe" :family "courier"))))
     (term-default ((t (:stipple nil :background "white" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "adobe" :family "courier"))))
     (term-default-bg ((t (:stipple nil :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "adobe" :family "courier"))))
     (term-default-bg-inv ((t (:stipple nil :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "adobe" :family "courier"))))
     (term-default-bold-face ((t (:bold t :background "snow2" :foreground "darkslategray" :weight bold))))
     (term-default-face ((t (:background "snow2" :foreground "darkslategray"))))
     (term-default-fg ((t (:stipple nil :background "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "adobe" :family "courier"))))
     (term-default-fg-inv ((t (:stipple nil :background "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "adobe" :family "courier"))))
     (term-default-inv-face ((t (:background "darkslategray" :foreground "snow2"))))
     (term-default-ul-face ((t (:background "snow2" :foreground "darkslategray" :underline t))))
     (term-green ((t (:foreground "green" :foundry "adobe" :family "courier"))))
     (term-green-bold-face ((t (:bold t :background "snow2" :foreground "green" :weight bold))))
     (term-green-face ((t (:foreground "green"))))
     (term-green-inv-face ((t (:background "green"))))
     (term-green-ul-face ((t (:background "snow2" :foreground "green" :underline t))))
     (term-greenbg ((t (:background "green" :foundry "adobe" :family "courier"))))
     (term-invisible ((t (:stipple nil :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "adobe" :family "courier"))))
     (term-invisible-inv ((t (:stipple nil :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "adobe" :family "courier"))))
     (term-magenta ((t (:foreground "magenta" :foundry "adobe" :family "courier"))))
     (term-magenta-bold-face ((t (:bold t :background "snow2" :foreground "magenta" :weight bold))))
     (term-magenta-face ((t (:foreground "magenta"))))
     (term-magenta-inv-face ((t (:background "magenta"))))
     (term-magenta-ul-face ((t (:background "snow2" :foreground "magenta" :underline t))))
     (term-magentabg ((t (:background "magenta" :foundry "adobe" :family "courier"))))
     (term-red ((t (:foreground "red" :foundry "adobe" :family "courier"))))
     (term-red-bold-face ((t (:bold t :background "snow2" :foreground "red" :weight bold))))
     (term-red-face ((t (:foreground "red"))))
     (term-red-inv-face ((t (:background "red"))))
     (term-red-ul-face ((t (:background "snow2" :foreground "red" :underline t))))
     (term-redbg ((t (:background "red" :foundry "adobe" :family "courier"))))
     (term-underline ((t (:underline t :foundry "adobe" :family "courier"))))
     (term-white ((t (:foreground "white" :foundry "adobe" :family "courier"))))
     (term-white-bold-face ((t (:bold t :background "snow2" :foreground "white" :weight bold))))
     (term-white-face ((t (:foreground "white"))))
     (term-white-inv-face ((t (:background "snow2"))))
     (term-white-ul-face ((t (:background "snow2" :foreground "white" :underline t))))
     (term-whitebg ((t (:background "white" :foundry "adobe" :family "courier"))))
     (term-yellow ((t (:foreground "yellow" :foundry "adobe" :family "courier"))))
     (term-yellow-bold-face ((t (:bold t :background "snow2" :foreground "yellow" :weight bold))))
     (term-yellow-face ((t (:foreground "yellow"))))
     (term-yellow-inv-face ((t (:background "yellow"))))
     (term-yellow-ul-face ((t (:background "snow2" :foreground "yellow" :underline t))))
     (term-yellowbg ((t (:background "yellow" :foundry "adobe" :family "courier"))))
     (tex-math-face ((t (:foreground "RosyBrown"))))
     (texinfo-heading-face ((t (:foreground "Blue"))))
     (text-cursor ((t (:background "Red3" :foreground "black"))))
     (tool-bar ((t (:foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:background "lightyellow" :foreground "black" :family "Sans Serif"))))
     (trailing-whitespace ((t (:background "red1"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (vc-annotate-face-0046FF ((t (:background "black" :foreground "wheat"))))
     (vcursor ((t (:background "cyan" :foreground "blue" :underline t))))
     (vertical-border ((t (:background "white" :foreground "white"))))
     (vertical-divider ((t (:background "Gray"))))
     (vhdl-font-lock-attribute-face ((t (:foreground "Orchid"))))
     (vhdl-font-lock-directive-face ((t (:foreground "CadetBlue"))))
     (vhdl-font-lock-enumvalue-face ((t (:foreground "Gold4"))))
     (vhdl-font-lock-function-face ((t (:foreground "Orchid4"))))
     (vhdl-font-lock-generic-/constant-face ((t (:foreground "Gold3"))))
     (vhdl-font-lock-prompt-face ((t (:bold t :foreground "Red" :weight bold))))
     (vhdl-font-lock-reserved-words-face ((t (:bold t :foreground "Orange" :weight bold))))
     (vhdl-font-lock-translate-off-face ((t (:background "LightGray"))))
     (vhdl-font-lock-type-face ((t (:foreground "ForestGreen"))))
     (vhdl-font-lock-variable-face ((t (:foreground "Grey50"))))
     (vhdl-speedbar-architecture-face ((t (:foreground "Blue"))))
     (vhdl-speedbar-architecture-selected-face ((t (:foreground "Blue" :underline t))))
     (vhdl-speedbar-configuration-face ((t (:foreground "DarkGoldenrod"))))
     (vhdl-speedbar-configuration-selected-face ((t (:foreground "DarkGoldenrod" :underline t))))
     (vhdl-speedbar-entity-face ((t (:foreground "ForestGreen"))))
     (vhdl-speedbar-entity-selected-face ((t (:foreground "ForestGreen" :underline t))))
     (vhdl-speedbar-instantiation-face ((t (:foreground "Brown"))))
     (vhdl-speedbar-instantiation-selected-face ((t (:foreground "Brown" :underline t))))
     (vhdl-speedbar-package-face ((t (:foreground "Grey50"))))
     (vhdl-speedbar-package-selected-face ((t (:foreground "Grey50" :underline t))))
     (vhdl-speedbar-subprogram-face ((t (:foreground "Orchid4"))))
     (viper-minibuffer-emacs-face ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-minibuffer-insert-face ((t (:background "pink" :foreground "Black"))))
     (viper-minibuffer-vi-face ((t (:background "grey" :foreground "DarkGreen"))))
     (viper-replace-overlay-face ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-search-face ((t (:background "khaki" :foreground "Black"))))
     (vm-header-content-face ((t (:italic t :foreground "gray80" :slant italic))))
     (vm-header-from-face ((t (:italic t :background "#65889C" :foreground "cyan" :slant italic))))
     (vm-header-name-face ((t (:foreground "cyan"))))
     (vm-header-subject-face ((t (:foreground "cyan"))))
     (vm-header-to-face ((t (:italic t :foreground "cyan" :slant italic))))
     (vm-message-cited-face ((t (:foreground "Gray80"))))
     (vm-summary-face-1 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-2 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-3 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-4 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-highlight-face ((t (:foreground "White"))))
     (vm-xface ((t (:background "white" :foreground "black"))))
     (vmpc-pre-sig-face ((t (:foreground "forestgreen"))))
     (vmpc-sig-face ((t (:foreground "steelblue"))))
     (vvb-face ((t (:background "pink" :foreground "black"))))
     (w3m-anchor-face ((t (:bold t :foreground "DodgerBlue1" :weight bold))))
     (w3m-arrived-anchor-face ((t (:bold t :foreground "DodgerBlue3" :weight bold))))
     (w3m-header-line-location-content-face ((t (:background "dark olive green" :foreground "wheat"))))
     (w3m-header-line-location-title-face ((t (:background "dark olive green" :foreground "beige"))))
     (white ((t (:foreground "white"))))
     (widget ((t (:background "Gray80" :foreground "black"))))
     (widget-button ((t (:bold t :weight bold :family "courier"))))
     (widget-button-pressed ((t (:foreground "red"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "yellow3" :foreground "black"))))
     (widget-inactive ((t (:foreground "yellow"))))
     (widget-single-line-field ((t (:background "green3" :foreground "black"))))
     (woman-addition ((t (:foreground "orange"))))
     (woman-bold ((t (:bold t :foreground "green2" :weight bold :family "Arial"))))
     (woman-italic ((t (:italic t :underline t :slant italic :family "Arial"))))
     (woman-unknown ((t (:foreground "cyan"))))
     (x-face ((t (:background "white" :foreground "black"))))
     (x-symbol-adobe-fontspecific-face ((t (nil))))
     (x-symbol-face ((t (nil))))
     (x-symbol-heading-face ((t (:bold t :foreground "green4" :underline t :weight bold))))
     (x-symbol-info-face ((t (:foreground "green4"))))
     (x-symbol-invisible-face ((t (nil))))
     (x-symbol-revealed-face ((t (:background "pink"))))
     (xrdb-option-name-face ((t (:foreground "red"))))
     (xrdb-option-value-face ((t (:bold t :foreground "magenta" :weight bold))))
     (xref-keyword-face ((t (:foreground "blue"))))
     (xref-list-default-face ((t (nil))))
     (xref-list-pilot-face ((t (:foreground "navy"))))
     (xref-list-symbol-face ((t (:foreground "navy"))))
     (xxml-emph-1-face ((t (:background "lightyellow"))))
     (xxml-emph-2-face ((t (:background "lightyellow"))))
     (xxml-header-1-face ((t (:background "seashell1" :foreground "MediumAquamarine"))))
     (xxml-header-2-face ((t (:background "seashell1" :foreground "SkyBlue"))))
     (xxml-header-3-face ((t (:background "seashell1"))))
     (xxml-header-4-face ((t (:background "seashell1"))))
     (xxml-interaction-face ((t (:background "lightcyan"))))
     (xxml-rug-face ((t (:background "cyan"))))
     (xxml-sparkle-face ((t (:background "yellow"))))
     (xxml-unbreakable-space-face ((t (:foreground "grey" :underline t))))
     (yas/field-debug-face ((t (nil))))
     (yas/field-highlight-face ((t (:background "lightyellow2"))))
     (yellow ((t (:foreground "yellow"))))
     (zmacs-region ((t (:background "lightgoldenrod2")))))))
